// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using groceries_helper.Persistence;

#nullable disable

namespace groceries_helper.Migrations
{
    [DbContext(typeof(GroceryHelperDbContext))]
    partial class GroceryHelperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("groceries_helper.Persistence.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesPer100Gram")
                        .HasColumnType("integer")
                        .HasColumnName("calories_per100gram");

                    b.Property<int>("CarbsPer100Gram")
                        .HasColumnType("integer")
                        .HasColumnName("carbs_per100gram");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FatsPer100Gram")
                        .HasColumnType("integer")
                        .HasColumnName("fats_per100gram");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("ProteinsPer100Gram")
                        .HasColumnType("integer")
                        .HasColumnName("proteins_per100gram");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_ingredients_created_at");

                    b.HasIndex("IsActive", "Id")
                        .HasDatabaseName("ix_ingredients_is_active_id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("groceries_helper.Persistence.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MealType")
                        .HasColumnType("integer")
                        .HasColumnName("meal_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_recipes_created_at");

                    b.HasIndex("IsActive", "Id")
                        .HasDatabaseName("ix_recipes_is_active_id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("groceries_helper.Persistence.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_of_measure_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_recipe_ingredients_created_at");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipe_ingredients_ingredient_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id");

                    b.HasIndex("UnitOfMeasureId")
                        .HasDatabaseName("ix_recipe_ingredients_unit_of_measure_id");

                    b.HasIndex("IsActive", "Id")
                        .HasDatabaseName("ix_recipe_ingredients_is_active_id");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("groceries_helper.Persistence.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_unit_of_measure");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_unit_of_measure_created_at");

                    b.HasIndex("IsActive", "Id")
                        .HasDatabaseName("ix_unit_of_measure_is_active_id");

                    b.ToTable("unit_of_measure", (string)null);
                });

            modelBuilder.Entity("groceries_helper.Persistence.Models.RecipeIngredient", b =>
                {
                    b.HasOne("groceries_helper.Persistence.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_ingredients_ingredient_id");

                    b.HasOne("groceries_helper.Persistence.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id");

                    b.HasOne("groceries_helper.Persistence.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_unit_of_measure_unit_of_measure_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("groceries_helper.Persistence.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
